language: ruby
rvm:
    2.3.3
before_script:
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - rake
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT    
